#!/bin/bash
#
# Shared functionality between GitHub utilities

set -e

# Load config file
source github.cfg

# Check args and initialize project info
if [ $# -ne 2 ]; then
    echo "Error: Wrong args, expected <project_name> <description>"
    exit 1
fi
project_name=$1
description=$2
