#!/bin/bash
#
#
# Create a github repository

source common

curl https://api.github.com/user/repos \
     --silent \
     -u $username \
     -d "{\"name\":\"$project_name\",\"description\":\"$description\"}" \
     > /dev/null

