#!/bin/bash
#
# Add a collaborator to an existing github repo

source common

collaborator_username=$2
curl -X PUT \
     "https://api.github.com/repos/$username/$project_name/collaborators/$collaborator_username" \
      -u $username \
      -d ''