#!/bin/bash
#
#
# Create a skeleton project locally

source common

# Determine and create the project directory
# Error if directory exists (so we don't risk overwriting anything)
project_path="$workspace_base_dir/$project_name"
if [ -d $project_path ]; then
  echo "Error: Directory already exists, $project_path"
  exit 2
fi
mkdir $project_path

# Create default README.md
readme_content="# $project_name\n$description\n"
echo -en $readme_content >> "$project_path/README.md"

# Create default .gitignore
gitignore_content=".idea\n"
echo -en $gitignore_content >> "$project_path/.gitignore"

